#!/usr/bin/env python3
"""PHP SDK emitter.

Language-neutral spec parsing, grouping, aliasing, and the operations docs table
live in the vendored ``scripts/_sdkgen/core.py`` (synced from the API repo). This
file only maps OpenAPI types to PHP types and writes the PHP artifacts:
``src/Operations.php`` (runtime metadata + OperationId constants) and
``src/Generated.php`` (PHPDoc ``@method`` annotations for IDE/PHPStan).
"""
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _sdkgen import core  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SPEC = ROOT / "openapi" / "public.json"
SPEC_PATH = Path(os.environ.get("CRAWLORA_OPENAPI_SPEC", DEFAULT_SPEC))

# PHP reserved words; a generated method name that collides gets a trailing "_".
PHP_KEYWORDS = frozenset(
    """
    abstract and array as break callable case catch class clone const continue
    declare default do echo else elseif empty enddeclare endfor endforeach endif
    endswitch endwhile enum extends final finally fn for foreach function global
    goto if implements include instanceof insteadof interface isset list match
    namespace new or print private protected public readonly require return static
    switch throw trait try unset use var while xor yield true false null
    """.split()
)


def php_case(parts):
    """lowerCamelCase from word parts: ["room","reviews"] -> "roomReviews"."""
    if not parts:
        return "call"
    head = parts[0]
    tail = [p[:1].upper() + p[1:] for p in parts[1:]]
    return head + "".join(tail)


POLICY = core.NamingPolicy(
    case_fn=php_case,
    dedup_sep="",
    keywords=PHP_KEYWORDS,
    tag_group_overrides={
        "AppStore": "appStore",
        "CoinGecko": "coinGecko",
        "GooglePlay": "googlePlay",
        "ProductHunt": "productHunt",
        "SimilarWeb": "similarWeb",
        "SpotifyPodcasts": "spotifyPodcasts",
        "TikTok": "tiktok",
        "YouTube": "youtube",
    },
)


def php_literal(value, indent=0):
    """Serialize a JSON-ish Python value as a PHP array literal with string keys."""
    pad = "    " * indent
    inner = "    " * (indent + 1)
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        return php_string(value)
    if isinstance(value, bool):  # pragma: no cover - handled above
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, (list, tuple)):
        if not value:
            return "[]"
        items = [f"{inner}{php_literal(item, indent + 1)}" for item in value]
        return "[\n" + ",\n".join(items) + f",\n{pad}]"
    if isinstance(value, dict):
        if not value:
            return "[]"
        items = [
            f"{inner}{php_string(str(k))} => {php_literal(v, indent + 1)}"
            for k, v in value.items()
        ]
        return "[\n" + ",\n".join(items) + f",\n{pad}]"
    raise TypeError(f"cannot serialize {type(value)!r} to a PHP literal")


def php_string(value):
    """Single-quoted PHP string literal."""
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def php_type(param):
    """Map an OpenAPI parameter to a PHP type for docs/PHPDoc."""
    enum_values = param.get("enum") or []
    if enum_values:
        return "|".join(php_string(str(value)) for value in enum_values)
    typ = param.get("type")
    if typ == "integer":
        return "int"
    if typ == "number":
        return "float"
    if typ == "boolean":
        return "bool"
    if typ == "array":
        return f"array<{php_type(param.get('items', {'type': 'string'}))}>"
    return "string"


def render_operations(model):
    const_lines = []
    used = set()
    for operation_id, meta in sorted(model.meta.items(), key=lambda item: item[1]["type_base"]):
        const = "_".join(core.words(meta["type_base"])).upper() or "OPERATION"
        base = const
        i = 2
        while const in used:
            const = f"{base}_{i}"
            i += 1
        used.add(const)
        const_lines.append(f"    public const {const} = {php_string(operation_id)};")

    return (
        "<?php\n\n"
        "// Generated by scripts/generate.py. Do not edit manually.\n\n"
        "declare(strict_types=1);\n\n"
        "namespace Crawlora;\n\n"
        "/**\n"
        " * Normalized, language-neutral runtime operation metadata generated from\n"
        " * the shared OpenAPI contract. The hand-written Client reads these arrays at\n"
        " * runtime for dispatch and validation.\n"
        " */\n"
        "final class Operations\n"
        "{\n"
        "    /** @var array<string,array<string,mixed>> */\n"
        f"    public const OPERATIONS = {php_literal(model.operations, 1)};\n\n"
        "    /** @var array<string,array<string,string>> */\n"
        f"    public const GROUPS = {php_literal(model.groups, 1)};\n\n"
        f"    public const OPERATION_COUNT = {model.operation_count};\n\n"
        "    /** @var array<int,string> */\n"
        f"    public const OPERATION_IDS = {php_literal(list(model.operations.keys()), 1)};\n\n"
        "    /**\n"
        "     * Operation metadata by id, or null if unknown. Typed accessor so callers\n"
        "     * (and PHPStan) see a plain array rather than the huge const literal.\n"
        "     *\n"
        "     * @return array<string,mixed>|null\n"
        "     */\n"
        "    public static function get(string $operationId): array|null\n"
        "    {\n"
        "        /** @var array<string,array<string,mixed>> $operations */\n"
        "        $operations = self::OPERATIONS;\n"
        "        return $operations[$operationId] ?? null;\n"
        "    }\n\n"
        "    /** @return array<string,array<string,string>> */\n"
        "    public static function groups(): array\n"
        "    {\n"
        "        /** @var array<string,array<string,string>> $groups */\n"
        "        $groups = self::GROUPS;\n"
        "        return $groups;\n"
        "    }\n\n"
        "    /**\n"
        "     * All operation metadata by id. Typed accessor so callers (and PHPStan)\n"
        "     * see a plain array rather than the huge const literal.\n"
        "     *\n"
        "     * @return array<string,array<string,mixed>>\n"
        "     */\n"
        "    public static function all(): array\n"
        "    {\n"
        "        /** @var array<string,array<string,mixed>> $operations */\n"
        "        $operations = self::OPERATIONS;\n"
        "        return $operations;\n"
        "    }\n"
        "}\n\n"
        "/**\n"
        " * SCREAMING_SNAKE_CASE constants for every operation id, so editors\n"
        " * autocomplete them: $client->request(OperationId::BING_SEARCH, [...]).\n"
        " */\n"
        "final class OperationId\n"
        "{\n"
        + "\n".join(const_lines)
        + "\n}\n"
    )


def render_generated(model):
    """PHPDoc @method annotations: one group accessor class per group with a
    @method line per operation, plus @property lines on the Client mixin so
    ``$client->bing->search([...])`` is discoverable by IDEs and PHPStan."""
    lines = [
        "<?php",
        "",
        "// Generated by scripts/generate.py. Do not edit manually.",
        "",
        "declare(strict_types=1);",
        "",
        "namespace Crawlora\\Generated;",
        "",
    ]
    for group_name, methods in model.groups.items():
        klass = core.type_name(group_name, "group")
        lines.append("/**")
        for method_name, operation_id in methods.items():
            meta = model.meta[operation_id]
            params = []
            for param in meta["params"]:
                php = "array" if param.get("in") == "body" else php_type(param)
                params.append(f"{php} ${param['name']}")
            arglist = ", ".join(params)
            note = f" {meta['note']}" if meta["note"] else ""
            lines.append(
                f" * @method mixed {method_name}(array $params = [], array $options = []) "
                f"{operation_id} ({meta['method']} {meta['path']}){note}"
            )
            if arglist:
                lines.append(f" *   params: {arglist}")
        lines.append(" */")
        lines.append(f"abstract class {klass} {{}}")
        lines.append("")

    # A @property mixin listing every group accessor on the Client.
    lines.append("/**")
    for group_name in model.groups:
        klass = core.type_name(group_name, "group")
        lines.append(f" * @property-read \\Crawlora\\Generated\\{klass} ${group_name}")
    lines.append(" */")
    lines.append("abstract class ClientGroups {}")
    lines.append("")
    return "\n".join(lines)


def render_client_stub(model):
    """PHPStan stub augmenting the hand-written Client with a @property-read for
    every group accessor. PHPStan does not pull @property-read tags through a
    @mixin target's class docblock, so they are declared here directly on Client.
    """
    lines = [
        "<?php",
        "",
        "// Generated by scripts/generate.py. Do not edit manually.",
        "",
        "namespace Crawlora;",
        "",
        "/**",
    ]
    for group_name in model.groups:
        klass = core.type_name(group_name, "group")
        lines.append(f" * @property-read \\Crawlora\\Generated\\{klass} ${group_name}")
    lines.append(" */")
    lines.append("final class Client {}")
    lines.append("")
    return "\n".join(lines)


def main():
    if not SPEC_PATH.exists():
        raise SystemExit(f"public OpenAPI spec not found: {SPEC_PATH}")
    spec = json.loads(SPEC_PATH.read_text())
    (ROOT / "openapi").mkdir(exist_ok=True)
    target_spec = ROOT / "openapi" / "public.json"
    if SPEC_PATH.resolve() != target_spec.resolve():
        target_spec.write_text(SPEC_PATH.read_text())

    model = core.build_model(spec, POLICY)

    (ROOT / "src").mkdir(parents=True, exist_ok=True)
    (ROOT / "src" / "Operations.php").write_text(render_operations(model))
    (ROOT / "src" / "Generated.php").write_text(render_generated(model))
    (ROOT / ".phpstan").mkdir(exist_ok=True)
    (ROOT / ".phpstan" / "Client.stub").write_text(render_client_stub(model))
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "operations.md").write_text(
        core.operation_docs(model, title="Crawlora PHP SDK Operations", type_render=php_type)
    )


if __name__ == "__main__":
    main()
